[versions]
agp = "8.6.0"
androidx_test = "1.7.0"
androidx_test_ext = "1.3.0"
appcompat = "1.7.1"
compile_sdk_version = "36"
constraint_layout = "2.2.1"
core_ktx = "1.16.0"
espresso_core = "3.7.0"
junit = "4.13.2"
kotlin = "1.9.23"
min_sdk_version = "24"
vanniktech-maven-publish = "0.33.0"
target_sdk_version = "36"
recyclerViewVersion = "1.2.0-alpha04"
gsonVersion = "2.8.6"

[libraries]
junit = { module = "junit:junit", version.ref = "junit" }
androidx_appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx_constraint_layout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraint_layout" }
androidx_core_ktx = { module = "androidx.core:core-ktx", version.ref = "core_ktx" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerViewVersion" }
google-gson = { module = "com.google.code.gson:gson", version.ref = "gsonVersion" }
androidx_test_rules = { module = "androidx.test:rules", version.ref = "androidx_test" }
androidx_test_runner = { module = "androidx.test:runner", version.ref = "androidx_test" }
androidx_test_ext_junit = { module = "androidx.test.ext:junit", version.ref = "androidx_test_ext" }
androidx_test_ext_junit_ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "androidx_test_ext" }
espresso_core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso_core" }
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kgp = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
vanniktech-maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech-maven-publish" }